application: bench-equal-sums
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
- url: /static
  static_dir: static
  expiration: "1h"
  